version: '3'
services:
  mysql:
    build:
      context: .
      dockerfile: .docker/mysql/Dockerfile
    port:
      - "3306:3306"
    volumes:
      - "/var/lib/mysql:/var/lib/mysql"
  nginx:
    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile
    ports:
      - "80:80"
    expose:
      - "80"
    stdin_open: true
    tty: true
    volumes:
      - "/var/lib/mysql:/var/lib/mysql"
    command: nginx
  php-fpm:
    build:
      context: .
      dockerfile: .docker/php-fpm/Dockerfile
    expose:
      - "9000"
    volumes:
      - "./:/opt/app"
    stdin_open: true
    tty: true
    command: php-fpm
